spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: false
jwt:
  secret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351